export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST"
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS"
export const CART_ADD_ITEM_FAIL = "CART_ADD_ITEM_FAIL"

export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"

export const CART_UPDATE_REQUEST = "CART_UPDATE_REQUEST"
export const CART_UPDATE_SUCCESS = "CART_UPDATE_SUCCESS"
export const CART_UPDATE_FAIL = "CART_UPDATE_FAIL"

export const CART_GET_ITEMS_REQUEST = "CART_GET_ITEMS_REQUEST"
export const CART_GET_ITEMS_SUCCESS = "CART_GET_ITEMS_SUCCESS"
export const CART_GET_ITEMS_FAIL = "CART_GET_ITEMS_FAIL"

export const CART_RESET = "CART_RESET"

export const CART_SAVE_SHIPPING_DETAILS = "CART_SAVE_SHIPPING_DETAILS"

export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD"
