export const ORDER_PLACE_REQUEST = "ORDER_PLACE_REQUEST"
export const ORDER_PLACE_SUCCESS = "ORDER_PLACE_SUCCESS"
export const ORDER_PLACE_FAIL = "ORDER_PLACE_FAIL"
export const ORDER_PLACE_RESET = "ORDER_PLACE_RESET"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"
export const ORDER_DETAILS_RESET = "ORDER_DETAILS_RESET"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

export const GET_MY_ORDERS_REQUEST = "GET_MY_ORDERS_REQUEST"
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS"
export const GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL"
export const GET_MY_ORDERS_RESET = "GET_MY_ORDERS_RESET"

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST"
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL"

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST"
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS"
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL"

export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST"
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS"
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL"
export const ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET"
